### ISSUE TITLE
Latest Commit - Deprecation and broken workflow

### ISSUE THREAD

**Issue by LeeFrancis** [electrode-io/electrode-archetype-react-component#21]
With the latest commit (e8a5a84) the yeoman generator electrode-component is broken.
Which breaks the whole workflow documented [here](http://www.electrode.io/docs/low_level_components.html)

I am pinning the npm version for electrode-archetype-react-component to 1.1.3 after the yo generator bombs out until I figure out what this new workflow is.
Any plans to update the doc?

**Comment by ananavati** [comment]
@LeeFrancis 

sorry for the inconvenience, we are working on consolidating all core electrode modules into one repo https://github.com/electrode-io/electrode for: 

* ease of use.
* easily discoverable.
* easy to maintain.

commits for fix:
* https://github.com/electrode-io/electrode/commit/ab7eba461ca6ad8e7dcbd4a6fb85265193447510 
* https://github.com/electrode-io/electrode/commit/06a8076d7af1ff375a5362c5169433b6c9ea48f1

these above commits should fix the issue, all you would have to do is re-rerun `npm install` on your component or re-run `yo electrode-component`
